author = Artur Tarassow
email = atecon@posteo.de
version = 2.0
date = 2021-03-07
description = Panel threshold model of Hansen (JoE, 1999)
tags = C23
min-version = 2020b
public = estimateTpm plotTpm
help = Threshold_Panel_help.txt
sample-script = Threshold_Panel_sample.inp
data-requirement = needs-panel-data
data-files = ThresholdPanel_data_joe99.gdt
depends = wooldridge_test_serial
